class MoveAitaCitiesToDb < ActiveRecord::Migration
  def self.up
    Iata.delete_all

    {
      "Albany, NY" => "ALB",
      "Albuquerque, NM" => "ABQ",
      "Atlanta, GA" => "ATL",
      "Anchorage, AK" => "ANC",
      "Austin, TX" => "AUS",
      "Baltimore, MD" => "BWI",
      "Bangor, ME" => "BGR",
      "Baton Rouge, LA" => "BTR",
      "Binghampton, NY" => "BGM",
      "Birmingham, AL" => "BHM",
      "Boston, MA" => "BOS",
      "Buffalo, NY" => "BUF",
      "Charleston, WV" => "CRW",
      "Charlotte, NC" => "CLT",
      "Chattanooga, TN" => "CHA",
      "Chicago, IL - MDW" => "MDW",
      "Chicago, IL - ORD" => "ORD",
      "Cincinnati, OH" => "CVG",
      "Cleveland, OH" => "CLE",
      "Columbus, OH" => "CMH",
      "Colorado Springs, CO" => "COS",
      "Dallas, TX" => "DFW",
      "Denver, CO" => "DEN",
      "Des Moines, IA" => "DSM",
      "Detroit, MI" => "DTW",
      "Fayetteville, NC" => "FAY",
      "Ft Lauderdale, FL" => "FLL",
      "Ft Myers, FL" => "RSW",
      "Ft Wayne, IN" => "FWA",
      "Greensboro, NC" => "GSO",
      "Hartford, CT" => "BDL",
      "Houston, TX - IAH" => "IAH",
      "Houston, TX - HOU" => "HOU",
      "Indianapolis, IN" => "IND",
      "Ithaca, NY" => "ITH",
      "Jacksonville, FL" => "JAX",
      "Kansas City, MO" => "MCI",
      "Key West, FL" => "EYW",
      "Knoxville, TN" => "TYS",
      "Las Vegas, NV" => "LAS",
      "Los Angeles, CA" => "LAX",
      "Louisville, KY" => "SDF",
      "Manchester, NH" => "MHT",
      "Memphis, TN" => "MEM",
      "Miami, FL" => "MIA",
      "Milwaukee, WI" => "MKE",
      "Minneapolis, MN" => "MSP",
      "Nashville, TN" => "BNA",
      "New Orleans, LA" => "MSY",
      "New York, NY - JFK" => "JFK",
      "New York, NY - LGA" => "LGA",
      "Newark, NJ" => "EWR",
      "Oakland, CA" => "OAK",
      "Oklahoma City, OK" => "OKC",
      "Ontario, CA" => "ONT",
      "Omaha, NE" => "OMA",
      "Orlando, FL" => "MCO",
      "Philadelphia, PA" => "PHL",
      "Phoenix, AZ" => "PHX",
      "Pittsburgh, PA" => "PIT",
      "Portland, OR" => "PDX",
      "Portland, ME" => "PWM",
      "Providence, RI" => "PVD",
      "Raleigh, NC" => "RDU",
      "Reno, NV" => "RNO",
      "Rochester, NY" => "ROC",
      "Sacramento, CA" => "SMF",
      "Salt Lake City, UT" => "SLC",
      "San Antonio, TX" => "SAT",
      "San Diego, CA" => "SAN",
      "San Francisco, CA" => "SFO",
      "San Jose, CA" => "SJC",
      "Santa Ana, CA" => "SNA",
      "Seattle, WA" => "SEA",
      "St Louis, MO" => "STL",
      "Syracuse, NY" => "SYR",
      "Tampa, FL" => "TPA",
      "Tulsa, OK" => "TUL",
      "Washington, DC - IAD" => "IAD", #need to make sure to change the D.C. to DC to adhere to Greyhound
      "Washington, DC - DCA" => "DCA",
      "White Plains, NY" => "HPN"
    }.each do |city, code|
      Iata.create! :iata_city => city, :iata_code => code
    end
  end

  def self.down
  end
end
